[build]
buildCommand = "npm install && npx prisma generate && DATABASE_URL=file:/tmp/build.db npx prisma db push && DATABASE_URL=file:/tmp/build.db npx next build"

[deploy]
startCommand = "mkdir -p /data && npx prisma db push && npm start"
